version: "3.8"

services:
  backend:
    build: ./backend
    container_name: amnezeus-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: amnezeus-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  # Если AmneziaWG запускается как отдельный контейнер, его можно добавить сюда:
  amneziawg:
    image: ghcr.io/w0rng/amnezia-wg-easy
    container_name: amneziawg
    environment:
      - LANG=en
      - WG_HOST=your_server_ip_or_dns
      - PASSWORD_HASH=your_bcrypt_hash
      - PORT=51821
      - WG_PORT=51820
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ~/.amnezia-wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
