version: "3.8"

volumes:
etc_wireguard:

services:
  backend:
    build: ./backend
    container_name: amnezeus-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: amnezeus-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  amnezia:
    build: ./amneziawg
    env_file:
      - .env
    container_name: amnezia
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
